### ISSUE TITLE
Having issue opening plugin

### ISSUE THREAD

**Issue by louiehernandez95** [elastic/generator-kibana-plugin#57] opened 2017-06-22 17:08 UTC
I tried following the instructions but when I run Kibana and click on the plugin I get the following message: (Note: my plugins name is Lane Search)

Error: Uncaught TypeError: Cannot read property 'get' of undefined (http://localhost:5601/bundles/Lane_Search.bundle.js?v=15117:1)
    at window.onerror (http://localhost:5601/bundles/commons.bundle.js?v=15117:77:8927)

I know this is probably my fault and not the actual code, but I'd like to get some feedback

**Comment by w33ble** [comment] 2017-06-22 17:17
It's not your fault, the code from the Kibana changed. It's a bug that was fixed with v7.0.0 of the generator, but you'll have to update your code. It's a pretty simple change though.

```
import uiModules from 'ui/modules';
```

Should simply become

```
import { uiModules } from 'ui/modules';
```

Then your app should run again.

**Closed as completed by w33ble** 2017-06-22 17:17 UTC

**Comment by louiehernandez95** [comment] 2017-06-22 17:26
Do i have the correct app.js file location?

C:\Users\lhernandez1\Documents\kibana-5.4.2-windows-x86\kibana\plugins\my-new-plugin\public\app

The code:

     import { uiModules } from 'ui/modules';

was already present.

**Comment by w33ble** [comment] 2017-06-22 18:27
Hrm... well that's unfortunate. Maybe I jumped to conclusions a little too fast. What did you change after you generated the plugin? Or perhaps is the code available somewhere I can look at it?

**Comment by w33ble** [comment] 2017-06-22 18:33
Also, if you open your browser's debugger, do you get an actual error message, ideally with a link off to the code somewhere? If you dive into the bundled code, you can probably trace is back to the actual error. If you can get the browser's debugger to take you there, it'll use the sourcemaps and show you exactly where the problem is.

**Comment by louiehernandez95** [comment] 2017-06-22 21:16
[error.zip](https://github.com/elastic/generator-kibana-plugin/files/1096198/error.zip)

I did't alter any code except name the plugin, I attached the .zip which contains the files that say I have an error with. I am little wet behind the ears in javascript so it is a little hard to pinpoint where exactly the problem is. Sorry for being a bother.

**Comment by w33ble** [comment] 2017-06-23 16:25
The error mentions a `Lane_Search.bundle.js` file, but I don't see that in your zip file. Also, the bundles aren't super helpful, since I'm pretty sure the lines and column numbers it's reporting are wrong.

Can you send me what you have in the `/public` folder?

EDIT: Looks like search.bundle.js is the right file. I can see the call, but I can't find the module in the commons bundle. In any event, seeing what you have in `/public` would be really helpful.

**Comment by louiehernandez95** [comment] 2017-06-23 16:42
[Public.zip](https://github.com/elastic/generator-kibana-plugin/files/1098455/Public.zip)
 
Attached is my public folder, thanks again for your help!

**Comment by w33ble** [comment] 2017-06-23 17:00
Ah, I see what happened. I misspoke earlier too...

So, you used the latest version of the generator, which is targeting Kibana v5.5.0 and higher, but you're trying to develop a plugin for v5.4.2.

You need to use version 6 of the generator, not the latest version on npm.

If you rather not re-generate, you can also simply change the modules import in `app.js`.

```
import { uiModules } from 'ui/modules';
```

Should simply become

```
import uiModules from 'ui/modules';
```

Sorry about that, I should have asked what version of Kibana you were using earlier. 

I'll add a compatibility matrix to the readme today too.

**Comment by louiehernandez95** [comment] 2017-06-23 17:37
Thanks it worked haha
you're the best!
