### ISSUE TITLE
generator fails

### ISSUE THREAD

**Issue by GuillaumeUnice** [elastic/generator-kibana-plugin#37] opened 2016-10-18 09:31 UTC
I have just install with yo and then run npm start.

my npm version : 3.8.6

```
npm start

> plugin_test@6.0.0-alpha1 start /home/gborg/Téléchargements/ELK_installer/plugin_test
> plugin-helpers start

 watching for changes  (300 files)
  log   [09:26:03.305] [info][listening] basePath Proxy running at https://localhost:5601/cvj
optmzr    log   [09:26:04.880] [warning] Plugin "cloudunit_kibana" was disabled because it expected Kibana version "0.0.0", and found "6.0.0-alpha1".
```

Where is the problem about?

`Plugin "cloudunit_kibana" was disabled because it expected Kibana version "0.0.0", and found "6.0.0-alpha1".`

Thanks for all

**Comment by lukasolson** [comment] 2016-10-20 23:37
Duplicate of https://github.com/elastic/generator-kibana-plugin/issues/36

**Closed as completed** 2016-10-21 08:53 UTC
